services:
  revcord:
    image: ghcr.io/meme-bros/revcord:latest
    volumes:
      - ./revcord.sqlite:/app/revcord.sqlite:rw
    environment:
      - DISCORD_TOKEN="INSERT_DISCORD_TOKEN_HERE"
      - REVOLT_TOKEN="INSERT_DISCORD_TOKEN_HERE"
    restart: unless-stopped
